- name: Provision ML environment
  hosts: localhost
  connection: local
  become: true
  collections:
    - community.general
    - community.docker

  roles:
    - ml_environment

- name: Configure MLflow server
  hosts: localhost
  roles:
    - mlflow_server

- name: Deploy model API
  hosts: localhost
  roles:
    - model_deploy
