- name: Provision ML environment
  hosts: ml
  collections:
    - community.general
    - community.docker
  
  roles:
    - ml_environment
  
- name: Configure MLflow server
  hosts: ml
  roles:
    - mlflow_server

- name: Deploy model API
  hosts: ml
  roles:
    - model_deploy