- name: Install system packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-venv
    - python3-pip
  become: true

- name: Create project directory
  file:
    path: /opt/ml_project
    state: directory
    owner: ubuntu

- name: Create virtual environment
  command: python3 -m venv /opt/ml_project/venv
  args:
    creates: /opt/ml_project/venv

- name: Install Python dependencies
  pip:
    requirements: /opt/ml_project/requirements.txt
    virtualenv: /opt/ml_project/venv
  notify: Upgrade pip

- name: Copy MLflow service unit file
  template:
    src: mlflow.service.j2
    dest: /etc/systemd/system/mlflow.service
  notify: Restart MLflow

- name: Ensure MLflow directory exists
  file:
    path: /var/lib/mlflow
    state: directory
    owner: ubuntu

- name: Start and enable MLflow service
  service:
    name: mlflow
    state: started
    enabled: true
